#!/usr/bin/env python3
"""Build a FAISS index from normalized CLIP text embeddings.

The text vectors are kept in a separate index for ASR/caption retrieval, but
they use the same CLIP space as the image vectors generated by the matching
image checkpoint.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import faiss
import numpy as np


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, required=True)
    ap.add_argument("--index-type", choices=["flat", "ivf"], default="flat")
    ap.add_argument("--nlist", type=int, default=256)
    args = ap.parse_args()

    emb_path = args.src / "text_embeddings.f32.npy"
    metadata_path = args.src / "text_embedding_metadata.json"
    model_manifest_path = args.src / "text_embedding_manifest.json"
    index_path = args.src / "faiss_text.index"
    if not emb_path.exists() or not metadata_path.exists() or not model_manifest_path.exists():
        raise SystemExit(
            "Missing text_embeddings.f32.npy, text_embedding_metadata.json, "
            "or text_embedding_manifest.json"
        )

    model_manifest = load_json(model_manifest_path)
    matrix = np.load(emb_path, mmap_mode="r")
    if matrix.ndim != 2 or matrix.shape[0] == 0:
        raise SystemExit(f"Invalid embedding matrix shape: {matrix.shape}")
    dim = int(matrix.shape[1])
    if int(model_manifest.get("dimension", -1)) != dim:
        raise SystemExit(
            f"Embedding dimension {dim} disagrees with manifest "
            f"{model_manifest.get('dimension')}"
        )
    if not model_manifest.get("normalized", False):
        raise SystemExit("Text embeddings must be L2-normalized before FAISS build")
    if not model_manifest.get("compatible_with_image_clip_space", False):
        raise SystemExit("Text embeddings are not marked compatible with image CLIP space")
    if not np.isfinite(matrix[: min(1000, len(matrix))]).all():
        raise SystemExit("Embedding matrix contains non-finite values")

    matrix = np.asarray(matrix, dtype="float32")

    if args.index_type == "flat":
        index = faiss.IndexFlatIP(dim)
        index.add(np.asarray(matrix, dtype="float32"))
    else:
        nlist = min(args.nlist, max(1, int(np.sqrt(len(matrix)))))
        quantizer = faiss.IndexFlatIP(dim)
        index = faiss.IndexIVFFlat(quantizer, dim, nlist, faiss.METRIC_INNER_PRODUCT)
        train_sample = np.asarray(
            matrix[: min(len(matrix), max(10_000, nlist * 40))], dtype="float32"
        )
        index.train(train_sample)
        index.add(np.asarray(matrix, dtype="float32"))

    faiss.write_index(index, str(index_path))
    manifest = {
        "index": index_path.name,
        "source_embeddings": emb_path.name,
        "metadata": metadata_path.name,
        "model_manifest": model_manifest_path.name,
        "model": model_manifest.get("model"),
        "pretrained": model_manifest.get("pretrained"),
        "space": model_manifest.get("space"),
        "index_type": args.index_type,
        "metric": "inner_product_on_l2_normalized_vectors",
        "dimension": dim,
        "n_vectors": int(index.ntotal),
        "source_sha256": sha256(emb_path),
        "search_not_implemented_in_this_stage": True,
    }
    (args.src / "text_faiss_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
